#!/bin/bash

echo 'appending kinect2_bridge launch to upstart file...'

if [ -d "/etc/ros/groovy" ];
then
    echo "groovy exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">\
    \t<arg name="base_name_tf" value="head_mount_kinect2"/>\
    </include>\
    </launch>:i' /etc/ros/groovy/robot.launch
fi

if [ -d "/etc/ros/hydro" ];
then
    echo "hydro exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">\
    \t<arg name="base_name_tf" value="head_mount_kinect2"/>\
    </include>\
    </launch>:i' /etc/ros/hydro/robot.launch
fi

if [ -d "/etc/ros/indigo" ];
then
    echo "indigo exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">\
    \t<arg name="base_name_tf" value="head_mount_kinect2"/>\
    </include>\
    </launch>:i' /etc/ros/indigo/robot.launch
fi

echo 'kinect2_bridge appended to upstart'
