#!/bin/bash

echo 'removing kinect2_bridge launch from upstart file...'

if [ -d "/etc/ros/groovy" ];
then
    echo "groovy exists..."
    sudo sed -i 's#<machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>##i' /etc/ros/groovy/robot.launch
    sudo sed -i 's#<include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">##i' /etc/ros/groovy/robot.launch
    sudo sed -i 's#<arg name="base_name_tf" value="head_mount_kinect2"/>##i' /etc/ros/groovy/robot.launch
    sudo sed -i 's#</include>##i' /etc/ros/groovy/robot.launch
fi

if [ -d "/etc/ros/hydro" ];
then
    echo "hydro exists..."
    sudo sed -i 's#<machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>##i' /etc/ros/hydro/robot.launch
    sudo sed -i 's#<include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">##i' /etc/ros/hydro/robot.launch
    sudo sed -i 's#<arg name="base_name_tf" value="head_mount_kinect2"/>##i' /etc/ros/hydro/robot.launch
    sudo sed -i 's#</include>##i' /etc/ros/hydro/robot.launch
fi

if [ -d "/etc/ros/indigo" ];
then
    echo "indigo exists..."
    sudo sed -i 's#<machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>##i' /etc/ros/indigo/robot.launch
    sudo sed -i 's#<include file="$(find kinect2_bridge)/launch/kinect2_bridge.launch">##i' /etc/ros/indigo/robot.launch
    sudo sed -i 's#<arg name="base_name_tf" value="head_mount_kinect2"/>##i' /etc/ros/indigo/robot.launch
    sudo sed -i 's#</include>##i' /etc/ros/indigo/robot.launch
fi

echo 'kinect2_bridge removed from upstart'
