#!/bin/bash

echo 'appending kinect2_bridge launch to upstart file...'

if [ -d "/etc/ros/groovy" ];
then
    echo "groovy exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <node machine="pr2-head" pkg="kinect2_bridge" type="kinect2_bridge" name="kinect2_bridge">\
    \t<param name="base_name_tf" value="head_mount_kinect2"/>\
    </node>\
    </launch>:i' /etc/ros/groovy/robot.launch
fi

if [ -d "/etc/ros/hydro" ];
then
    echo "hydro exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <node machine="pr2-head" pkg="kinect2_bridge" type="kinect2_bridge" name="kinect2_bridge">\
    \t<param name="base_name_tf" value="head_mount_kinect2"/>\
    </node>\
    </launch>:i' /etc/ros/hydro/robot.launch
fi

if [ -d "/etc/ros/indigo" ];
then
    echo "indigo exists..."
    sudo sed -i 's:</launch>:\
    <machine name="pr2-head" address="pr2-head" user="pr2-head" password="clearpath" env-loader="/home/pr2-head/kinect_ws/devel/env.sh"/>\
    <node machine="pr2-head" pkg="kinect2_bridge" type="kinect2_bridge" name="kinect2_bridge">\
    \t<param name="base_name_tf" value="head_mount_kinect2"/>\
    </node>\
    </launch>:i' /etc/ros/indigo/robot.launch
fi

echo 'kinect2_bridge appended to upstart'

# Add key to NUC
echo "Setting up SSH keys to NUC"
if [[ -e ~/.ssh/id_rsa.pub ]];
then
  echo "~/.ssh/id_rsa.pub detected."
  ssh-copy-id -i ~/.ssh/id_rsa.pub pr2-head@pr2-head || {
    echo "Error copying key to NUC."
    exit 1
  }
  echo "SSH key added to NUC."
else
  read -r -p "~/.ssh/id_rsa.pub not detected. Do you want to set up your SSH keys? [y/N] " response
  response = ${response,,}
  if [[ $response =~ ^(yes|y)$ ]];
  then
    ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  ssh-copy-id -i ~/.ssh/id_rsa.pub pr2-head@pr2-head || {
    echo "Error copying key to NUC."
    exit 1
  }
    echo "RSA key has been generated at ~/.ssh/id_rsa.pub and exported to the NUC."
  else
    echo "SSH keys have not been set. If you already have SSH keys generated, please manually export your key to the NUC using ssh-copy-id."
    exit 1
  fi
fi
